spring:
  application:
    name: example-service
  profiles:
    config:
      activate:
        on-profile: "localhost"
  main:
    allow-bean-definition-overriding: true
info:
  component: Example Service


server:
  port: 9788

---
spring:
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: example_schema
        format_sql: true
        use_sql_comments: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/example_database"
    username: postgres
    password: db_1994

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      orm:
        jdbc:
          bind: TRACE
    root: DEBUG

